window.configData = {
  title: '松外24届1班毕业地图',
  bl: '语文老师 高老师<br>数学老师 赵老师<br>英语老师 郑老师<br>物理老师 霍老师<br>化学老师 孔老师<br>生物老师 刘老师',
  br: '',
  tr: '励志将蹭吃蹭喝进行到底',
  blank: '这里没有我们的同志 蹭饭请找下家',
  bg: [],
};
window.classData = [{"id": 0, "name": "宋雨衡", "city": "Shanghai", "university": "复旦大学"}, 
  {"id": 1, "name": "刘新杰", "city": "Zhejiang", "university": "浙江大学"}, 
  {"id": 2, "name": "丛佳峻", "city": "Zhejiang", "university": "浙江大学"}, 
  {"id": 3, "name": "陈柏潼", "city": "Shanghai", "university": "上海交通大学"}, 
  {"id": 4, "name": "周鑫弛", "city": "Shanghai", "university": "上海交通大学"}, 
  {"id": 5, "name": "柳宗杰", "city": "Heilongjiang", "university": "哈尔滨工业大学"}, 
  {"id": 6, "name": "张明宇", "city": "Heilongjiang", "university": "哈尔滨工业大学"}, 
  {"id": 7, "name": "陈敬尧", "city": "Hunan", "university": "国防科技大学"}, 
  {"id": 8, "name": "王圣博", "city": "Beijing", "university": "北京航空航天大学"}, 
  {"id": 9, "name": "潘科皓", "city": "Beijing", "university": "北京理工大学"}, 
  {"id": 10, "name": "仪品瑶", "city": "Beijing", "university": "北京理工大学"}, 
  {"id": 11, "name": "余茉菡", "city": "Jiangsu", "university": "东南大学"}, 
  {"id": 12, "name": "杨博远", "city": "Jiangsu", "university": "东南大学"}, 
  {"id": 13, "name": "姚帅祺", "city": "Sichuan", "university": "电子科技大学"}, 
  {"id": 14, "name": "魏赫", "city": "Sichuan", "university": "电子科技大学"}, 
  {"id": 15, "name": "李尚朴", "city": "Hubei", "university": "武汉大学"}, 
  {"id": 16, "name": "宿雅淇", "city": "Shaanxi", "university": "西北工业大学"}, 
  {"id": 17, "name": "吴语晴", "city": "Tianjin", "university": "天津大学"}, 
  {"id": 18, "name": "张明浩", "city": "Tianjin", "university": "天津大学"}, 
  {"id": 19, "name": "朱凯泽", "city": "Beijing", "university": "北京邮电大学"}, 
  {"id": 20, "name": "钱禹衡", "city": "Beijing", "university": "北京邮电大学"}, 
  {"id": 21, "name": "何泽", "city": "Hunan", "university": "中南大学"}, 
  {"id": 22, "name": "李妍筱", "city": "Jilin", "university": "吉林大学"}, 
  {"id": 23, "name": "刘文博", "city": "Jilin", "university": "吉林大学"}, 
  {"id": 24, "name": "霍广宇", "city": "Jilin", "university": "吉林大学"}, 
  {"id": 25, "name": "王嘉琪", "city": "Beijing", "university": "北京科技大学"}, 
  {"id": 26, "name": "孙雅鹏", "city": "Heilongjiang", "university": "哈尔滨工程大学"}, 
  {"id": 27, "name": "郭鸣宇", "city": "Jiangsu", "university": "中国药科大学"}, 
  {"id": 28, "name": "孟璟峤", "city": "Beijing", "university": "中国传媒大学"}, 
  {"id": 29, "name": "王曦瑶", "city": "Shanghai", "university": "上海财经大学"}, 
  {"id": 30, "name": "李东鉴", "city": "Shaanxi", "university": "长安大学"}, 
  {"id": 31, "name": "张骥洋", "city": "Shandong", "university": "中国海洋大学"}, 
  {"id": 32, "name": "郭俊", "city": "Shanghai", "university": "东华大学"}, 
  {"id": 33, "name": "任心爱", "city": "Hubei", "university": "中南财经政法大学"}, 
  {"id": 34, "name": "杨占堃", "city": "Inner Mongol", "university": "内蒙古大学"}, 
  {"id": 35, "name": "毛新月", "city": "Shandong", "university": "中国石油大学（华东）"}, 
  {"id": 36, "name": "高子轩", "city": "Guizhou", "university": "贵州大学"}, 
  {"id": 37, "name": "李熠哲", "city": "Inner Mongol", "university": "内蒙古医科大学"}, 
  {"id": 38, "name": "宋博轩", "city": "Inner Mongol", "university": "内蒙古医科大学"}, 
  {"id": 39, "name": "韩雨衡", "city": "Beijing", "university": "首都师范大学"}, 
  {"id": 40, "name": "韩丹", "city": "Hainan", "university": "海南大学"}, 
  {"id": 41, "name": "田健齐", "city": "Jiangsu", "university": "南京农业大学"}, 
  {"id": 42, "name": "张宝斌", "city": "Liaoning", "university": "辽宁工程技术大学"}, 
  {"id": 43, "name": "尚思宇", "city": "Shaanxi", "university": "西北农林科技大学"}, 
  {"id": 44, "name": "李宣美", "city": "Jilin", "university": "长春理工大学"}, 
  {"id": 45, "name": "李浩鑫", "city": "Beijing", "university": "战略支援部队航天大学"}];
